name: ibmc_blood_metabograms
version: 1.0.0
description: "Program for analyze blood metabograms by IBMC"
publish_to: 'none'

dependencies:
  adaptive_theme: ^3.6.0
  auto_route: ^8.1.3
  get_it: ^7.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  sentry_flutter: ^8.1.0
  shared_preferences: ^2.2.3
  vector_graphics: ^1.1.11+1

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.3.4 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
