name: ibmc_blood_metabograms
version: 1.0.0
description: "Program for analyze blood metabograms by IBMC"

dependencies:
  auto_route: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  logger: ^2.2.0
  sentry_flutter: ^8.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.3.4 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700
    - family: Inter 
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
